=== Luis-e-rf/BASES_DATOS_AVANZADAS/carta_de_platos/carta.dtd
<!ELEMENT restaurante (menus*)>
<!ELEMENT menus (primeros_platos*, segundos_platos*, terceros_platos*)>
<!ELEMENT primeros_platos (primer_plato*)>
<!ELEMENT primer_plato (id_primer, Nombre_primer, precio_primer, observaciones_primer, avisos_primer)>
<!ELEMENT id_primer (#PCDATA)>
<!ELEMENT Nombre_primer (#PCDATA)>
<!ELEMENT precio_primer (#PCDATA)>
<!ELEMENT observaciones_primer (#PCDATA)>
<!ELEMENT avisos_primer (#PCDATA)>
<!ELEMENT segundos_platos (segundo_plato*)>
<!ELEMENT segundo_plato (id_segundo, Nombre_segundo, precio_segundo, observaciones_segundo, avisos_segundo)>
<!ELEMENT id_segundo (#PCDATA)>
<!ELEMENT Nombre_segundo (#PCDATA)>
<!ELEMENT precio_segundo (#PCDATA)>
<!ELEMENT observaciones_segundo (#PCDATA)>
<!ELEMENT avisos_segundo (#PCDATA)>
<!ELEMENT terceros_platos (tercer_plato*)>
<!ELEMENT tercer_plato (id_tercero, Nombre_tercero, precio_tercero, observaciones_tercero, avisos_tercero)>
<!ELEMENT id_tercero (#PCDATA)>
<!ELEMENT Nombre_tercero (#PCDATA)>
<!ELEMENT precio_tercero (#PCDATA)>
<!ELEMENT observaciones_tercero (#PCDATA)>
<!ELEMENT avisos_tercero (#PCDATA)>
<!-- <!ATTLIST Telef tipo CDATA #REQUIRED>-->

=== Luis-e-rf/BASES_DATOS_AVANZADAS/carta_de_platos/carta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE restaurante SYSTEM "carta.dtd">
<restaurante>
    <menus>
        <primeros_platos>
            <primer_plato>
                <id_primer>1</id_primer>
                <Nombre_primer>Mojarra</Nombre_primer>
                <precio_primer>35000</precio_primer>
                <observaciones_primer>Mojarra frita con ensalada y papa frita</observaciones_primer>
                <avisos_primer>la ensalada incluye oregano abstenerse si es alergico</avisos_primer>
            </primer_plato>
        </primeros_platos>
        <segundos_platos>
            <segundo_plato>
                <id_segundo>1</id_segundo>
                <Nombre_segundo>Carne en salsa</Nombre_segundo>
                <precio_segundo>37000</precio_segundo>
                <observaciones_segundo>Carne en salsa con arroz y papa criolla</observaciones_segundo>
                <avisos_segundo>el arroz incluye tomillo abstenerse si es alergico</avisos_segundo>
            </segundo_plato>
        </segundos_platos>
        <terceros_platos>
            <tercer_plato>
                <id_tercero>1</id_tercero>
                <Nombre_tercero>Carne en salsa</Nombre_tercero>
                <precio_tercero>37000</precio_tercero>
                <observaciones_tercero>Carne en salsa con arroz y papa criolla</observaciones_tercero>
                <avisos_tercero>el arroz incluye tomillo abstenerse si es alergico</avisos_tercero>
            </tercer_plato>
        </terceros_platos>
    </menus>
</restaurante>
